import { logo, servicesImage } from '../../assets/assets'

export function InvoiceDocument({ invoice }) {
  if (!invoice) {
    return null
  }

  const isBookingInvoice = invoice.invoiceType === 'booking'
  const storedCredit = Number(invoice.customerCreditAddedAmount || 0)

  return (
    <article className="overflow-hidden rounded-lg border border-slate-200 bg-white shadow-sm">
      <header className="relative overflow-hidden bg-black text-white">
        <img
          className="absolute inset-0 h-full w-full object-cover opacity-35"
          src={servicesImage}
          alt=""
          aria-hidden="true"
        />
        <div className="absolute inset-0 bg-[linear-gradient(90deg,rgba(0,0,0,0.98),rgba(0,0,0,0.88),rgba(127,29,29,0.74))]" />
        <div className="relative p-6 sm:p-8">
          <div className="flex flex-wrap items-start justify-between gap-5">
            <div>
              <div className="flex items-center gap-4">
                <span className="h-16 w-1 rounded-full bg-[var(--primary)]" />
                <img className="h-16 w-auto object-contain" src={logo} alt="AutoCare logo" />
                <div>
                  <p className="text-3xl font-black leading-tight">Auto<span className="text-[var(--primary)]">Care</span></p>
                  <p className="mt-1 text-xs font-bold uppercase text-slate-300">Parts & Service Management</p>
                </div>
              </div>
              <div className="mt-8">
                <p className="text-sm font-semibold text-slate-300">Your AutoCare {isBookingInvoice ? 'service' : 'sales'} invoice is ready.</p>
              </div>
            </div>
            <div className="text-left sm:text-right">
              <p className="text-xs font-black uppercase text-red-200">{isBookingInvoice ? 'Booking Invoice' : 'Sales Invoice'}</p>
              <h2 className="mt-2 text-3xl font-black leading-tight">{invoice.invoiceNumber}</h2>
              <p className="mt-2 text-sm font-semibold text-slate-300">{formatDate(invoice.invoiceDate)}</p>
            </div>
          </div>
        </div>
        <div className="relative h-1.5 bg-[var(--primary)]" />
      </header>

      <section className="grid gap-3 p-5 sm:grid-cols-3">
        <SummaryCard label="Customer" value={invoice.customerName} detail={invoice.customerEmail} />
        <SummaryCard label="Payment" value={invoice.paymentStatus} detail={`Via ${invoice.paymentMethod}`} />
        <SummaryCard
          label={storedCredit > 0 ? 'Stored Credit' : 'Balance'}
          value={formatMoney(storedCredit > 0 ? storedCredit : invoice.creditAmount)}
          detail={invoice.emailSent ? 'Email sent' : 'Email not sent'}
          tone={storedCredit > 0 ? 'green' : 'red'}
        />
      </section>

      <section className="px-5 pb-5">
        <div className="overflow-x-auto rounded-lg border border-slate-200">
          <table className="min-w-[620px] w-full text-left">
            <thead className="bg-slate-50 text-xs font-black uppercase text-slate-500">
              <tr>
                <th className="px-4 py-3">{isBookingInvoice ? 'Service' : 'Part'}</th>
                <th className="px-4 py-3">Qty</th>
                <th className="px-4 py-3">Rate</th>
                <th className="px-4 py-3 text-right">Total</th>
              </tr>
            </thead>
            <tbody>
              {(invoice.items ?? []).map((item) => (
                <tr className="border-t border-slate-100" key={item.salesInvoiceItemId}>
                  <td className="px-4 py-3">
                    <p className="text-sm font-black text-slate-950">{item.partName}</p>
                    <p className="mt-1 text-xs font-semibold text-slate-500">
                      {item.partNumber || 'Custom invoice line'}
                    </p>
                  </td>
                  <td className="px-4 py-3 text-sm font-bold text-slate-700">{item.quantity}</td>
                  <td className="px-4 py-3 text-sm font-bold text-slate-700">{formatMoney(item.unitPrice)}</td>
                  <td className="px-4 py-3 text-right text-sm font-black text-slate-950">{formatMoney(item.lineTotal)}</td>
                </tr>
              ))}
            </tbody>
          </table>
        </div>

        <div className="mt-5 grid gap-5 lg:grid-cols-[1fr_360px]">
          <div className="rounded-lg border border-red-100 bg-red-50 px-4 py-3 text-sm font-semibold text-slate-700">
            <p className="font-black text-red-600">Security Note</p>
            <p className="mt-1">This invoice was generated by AutoCare. Keep it for your purchase history and payment records.</p>
          </div>

          <div className="grid gap-2 rounded-lg border border-slate-200 bg-slate-50 p-4 text-sm font-bold text-slate-700">
            <InvoiceTotalRow label="Subtotal" value={formatMoney(invoice.subtotal)} />
            <InvoiceTotalRow label="Loyalty discount" value={formatMoney(invoice.discountAmount)} />
            <InvoiceTotalRow label="Customer credit used" value={formatMoney(invoice.customerCreditAppliedAmount)} />
            <InvoiceTotalRow label="Paid" value={formatMoney(invoice.paidAmount)} />
            <InvoiceTotalRow label="Total" value={formatMoney(invoice.totalAmount)} strong />
            <InvoiceTotalRow label="Balance" value={formatMoney(invoice.creditAmount)} danger />
            <InvoiceTotalRow label="Return / saved credit" value={formatMoney(storedCredit)} success={storedCredit > 0} />
          </div>
        </div>

        {invoice.notes && (
          <div className="mt-4 rounded-lg border border-slate-200 bg-white px-4 py-3">
            <p className="text-xs font-black uppercase text-slate-500">Notes</p>
            <p className="mt-1 whitespace-pre-wrap text-sm font-semibold text-slate-700">{invoice.notes}</p>
          </div>
        )}
      </section>
    </article>
  )
}

function SummaryCard({ detail, label, tone = 'slate', value }) {
  const toneClass = tone === 'red'
    ? 'border-red-100 bg-red-50'
    : tone === 'green'
      ? 'border-emerald-100 bg-emerald-50'
      : 'border-slate-200 bg-slate-50'
  return (
    <div className={`rounded-lg border px-4 py-3 ${toneClass}`}>
      <p className="text-xs font-black uppercase text-slate-500">{label}</p>
      <p className="mt-1 break-words text-base font-black text-slate-950">{value || 'Not set'}</p>
      <p className="mt-1 break-words text-xs font-semibold text-slate-500">{detail || 'Not recorded'}</p>
    </div>
  )
}

function InvoiceTotalRow({ danger = false, label, strong = false, success = false, value }) {
  return (
    <div className={`flex justify-between gap-4 ${danger ? 'text-red-600' : success ? 'text-emerald-700' : strong ? 'text-slate-950' : ''}`}>
      <span>{label}</span>
      <span>{value}</span>
    </div>
  )
}

function formatDate(value) {
  if (!value) {
    return 'Not set'
  }

  return new Intl.DateTimeFormat('en', {
    day: '2-digit',
    month: 'short',
    year: 'numeric',
  }).format(new Date(value))
}

function formatMoney(value) {
  return new Intl.NumberFormat('en-NP', {
    currency: 'NPR',
    maximumFractionDigits: 2,
    style: 'currency',
  }).format(Number(value || 0))
}
