using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace Servers.Migrations
{
    /// <inheritdoc />
    public partial class InitialAuthSchema : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.Sql("""
                CREATE TABLE IF NOT EXISTS "Users" (
                    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
                    "FullName" character varying(120) NOT NULL,
                    "Email" character varying(180) NOT NULL,
                    "PasswordHash" text NOT NULL,
                    "Phone" character varying(30) NOT NULL,
                    "Role" character varying(20) NOT NULL,
                    "CreatedAt" timestamp with time zone NOT NULL DEFAULT (NOW()),
                    CONSTRAINT "PK_Users" PRIMARY KEY ("Id")
                );
                """);

            migrationBuilder.Sql("""
                CREATE UNIQUE INDEX IF NOT EXISTS "IX_Users_Email" ON "Users" ("Email");
                """);

            migrationBuilder.Sql("""
                CREATE INDEX IF NOT EXISTS "IX_Users_Role" ON "Users" ("Role");
                """);
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropTable(
                name: "Users");
        }
    }
}
